// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.6
// source: messages.proto

package messages

import (
	actor "github.com/asynkron/protoactor-go/actor"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserAddItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=productId,proto3" json:"productId,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserAddItem) Reset() {
	*x = UserAddItem{}
	mi := &file_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserAddItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAddItem) ProtoMessage() {}

func (x *UserAddItem) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAddItem.ProtoReflect.Descriptor instead.
func (*UserAddItem) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{0}
}

func (x *UserAddItem) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *UserAddItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type UserCheckout struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReplyTo       *actor.PID             `protobuf:"bytes,1,opt,name=replyTo,proto3" json:"replyTo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserCheckout) Reset() {
	*x = UserCheckout{}
	mi := &file_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserCheckout) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCheckout) ProtoMessage() {}

func (x *UserCheckout) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCheckout.ProtoReflect.Descriptor instead.
func (*UserCheckout) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{1}
}

func (x *UserCheckout) GetReplyTo() *actor.PID {
	if x != nil {
		return x.ReplyTo
	}
	return nil
}

type SetPurchasePID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           *actor.PID             `protobuf:"bytes,1,opt,name=pid,proto3" json:"pid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetPurchasePID) Reset() {
	*x = SetPurchasePID{}
	mi := &file_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPurchasePID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPurchasePID) ProtoMessage() {}

func (x *SetPurchasePID) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPurchasePID.ProtoReflect.Descriptor instead.
func (*SetPurchasePID) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{2}
}

func (x *SetPurchasePID) GetPid() *actor.PID {
	if x != nil {
		return x.Pid
	}
	return nil
}

type AddItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=productId,proto3" json:"productId,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddItem) Reset() {
	*x = AddItem{}
	mi := &file_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddItem) ProtoMessage() {}

func (x *AddItem) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddItem.ProtoReflect.Descriptor instead.
func (*AddItem) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{3}
}

func (x *AddItem) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *AddItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type Checkout struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReplyTo       *actor.PID             `protobuf:"bytes,1,opt,name=replyTo,proto3" json:"replyTo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Checkout) Reset() {
	*x = Checkout{}
	mi := &file_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Checkout) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Checkout) ProtoMessage() {}

func (x *Checkout) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Checkout.ProtoReflect.Descriptor instead.
func (*Checkout) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{4}
}

func (x *Checkout) GetReplyTo() *actor.PID {
	if x != nil {
		return x.ReplyTo
	}
	return nil
}

type ProcessOrder struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReplyTo       *actor.PID             `protobuf:"bytes,1,opt,name=replyTo,proto3" json:"replyTo,omitempty"`
	Items         map[string]int32       `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	TotalPrice    float64                `protobuf:"fixed64,3,opt,name=totalPrice,proto3" json:"totalPrice,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessOrder) Reset() {
	*x = ProcessOrder{}
	mi := &file_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessOrder) ProtoMessage() {}

func (x *ProcessOrder) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessOrder.ProtoReflect.Descriptor instead.
func (*ProcessOrder) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{5}
}

func (x *ProcessOrder) GetReplyTo() *actor.PID {
	if x != nil {
		return x.ReplyTo
	}
	return nil
}

func (x *ProcessOrder) GetItems() map[string]int32 {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ProcessOrder) GetTotalPrice() float64 {
	if x != nil {
		return x.TotalPrice
	}
	return 0
}

type OrderConfirmed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=orderId,proto3" json:"orderId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderConfirmed) Reset() {
	*x = OrderConfirmed{}
	mi := &file_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderConfirmed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderConfirmed) ProtoMessage() {}

func (x *OrderConfirmed) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderConfirmed.ProtoReflect.Descriptor instead.
func (*OrderConfirmed) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{6}
}

func (x *OrderConfirmed) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

var File_messages_proto protoreflect.FileDescriptor

const file_messages_proto_rawDesc = "" +
	"\n" +
	"\x0emessages.proto\x12\bmessages\x1a\vactor.proto\"G\n" +
	"\vUserAddItem\x12\x1c\n" +
	"\tproductId\x18\x01 \x01(\tR\tproductId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\"4\n" +
	"\fUserCheckout\x12$\n" +
	"\areplyTo\x18\x01 \x01(\v2\n" +
	".actor.PIDR\areplyTo\".\n" +
	"\x0eSetPurchasePID\x12\x1c\n" +
	"\x03pid\x18\x01 \x01(\v2\n" +
	".actor.PIDR\x03pid\"C\n" +
	"\aAddItem\x12\x1c\n" +
	"\tproductId\x18\x01 \x01(\tR\tproductId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\"0\n" +
	"\bCheckout\x12$\n" +
	"\areplyTo\x18\x01 \x01(\v2\n" +
	".actor.PIDR\areplyTo\"\xc7\x01\n" +
	"\fProcessOrder\x12$\n" +
	"\areplyTo\x18\x01 \x01(\v2\n" +
	".actor.PIDR\areplyTo\x127\n" +
	"\x05items\x18\x02 \x03(\v2!.messages.ProcessOrder.ItemsEntryR\x05items\x12\x1e\n" +
	"\n" +
	"totalPrice\x18\x03 \x01(\x01R\n" +
	"totalPrice\x1a8\n" +
	"\n" +
	"ItemsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"*\n" +
	"\x0eOrderConfirmed\x12\x18\n" +
	"\aorderId\x18\x01 \x01(\tR\aorderIdB\x1bZ\x19ecommerce-actors/messagesb\x06proto3"

var (
	file_messages_proto_rawDescOnce sync.Once
	file_messages_proto_rawDescData []byte
)

func file_messages_proto_rawDescGZIP() []byte {
	file_messages_proto_rawDescOnce.Do(func() {
		file_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_messages_proto_rawDesc), len(file_messages_proto_rawDesc)))
	})
	return file_messages_proto_rawDescData
}

var file_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_messages_proto_goTypes = []any{
	(*UserAddItem)(nil),    // 0: messages.UserAddItem
	(*UserCheckout)(nil),   // 1: messages.UserCheckout
	(*SetPurchasePID)(nil), // 2: messages.SetPurchasePID
	(*AddItem)(nil),        // 3: messages.AddItem
	(*Checkout)(nil),       // 4: messages.Checkout
	(*ProcessOrder)(nil),   // 5: messages.ProcessOrder
	(*OrderConfirmed)(nil), // 6: messages.OrderConfirmed
	nil,                    // 7: messages.ProcessOrder.ItemsEntry
	(*actor.PID)(nil),      // 8: actor.PID
}
var file_messages_proto_depIdxs = []int32{
	8, // 0: messages.UserCheckout.replyTo:type_name -> actor.PID
	8, // 1: messages.SetPurchasePID.pid:type_name -> actor.PID
	8, // 2: messages.Checkout.replyTo:type_name -> actor.PID
	8, // 3: messages.ProcessOrder.replyTo:type_name -> actor.PID
	7, // 4: messages.ProcessOrder.items:type_name -> messages.ProcessOrder.ItemsEntry
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_messages_proto_init() }
func file_messages_proto_init() {
	if File_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_messages_proto_rawDesc), len(file_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_messages_proto_goTypes,
		DependencyIndexes: file_messages_proto_depIdxs,
		MessageInfos:      file_messages_proto_msgTypes,
	}.Build()
	File_messages_proto = out.File
	file_messages_proto_goTypes = nil
	file_messages_proto_depIdxs = nil
}
